[tool.poetry]
name = "thehive_app"
version = "0.1.0"
description = "TheHive integration with VAST"
authors = ["Tenzir <dev@tenzir.com>"]
license = "BSD-3-Clause"
packages = [{include = "app.py"}]

[tool.poetry.scripts]
run-app = "app:run"
alert-count = "app:alert_count"

[tool.poetry.dependencies]
python = "^3.10"
vast = {path = "../../../python", develop = true}
aiohttp = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
