version: "3"
services:
  quarto:
    build:
      target: quarto-bind-mount
    volumes:
      - ../..:/mnt/host
      - quarto:/home/vast/.cache
    environment:
      - HOST_UID
      - HOST_GID
    privileged: true

volumes:
  quarto:
    driver: local
