---
openapi: 3.0.0
info:
  description: VAST API
  version: 0.1
paths:
  /export:
    post:
      summary: Start a new query
      description: Create a new export query in VAST
      responses:
        200:
          description: Success.
          content: application/json
          schema:
            type: object
            properties:
              num_events:
                type: integer
              version:
                type: string
              events:
                type: array
                items: object
  /query:
    post:
      summary: Start a new query
      description: Create a new export query in VAST
      parameters:
        - in: query
          name: expression
          schema:
            type: string
          required: true
          description: Query string.
      responses:
        200:
          description: Success.
          content: application/json
          schema:
            type: object
            properties:
              id:
                type: string
  /query/{id}:
    get:
      summary: Start a new query
      description: Create a new export query in VAST
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The query ID.
        - in: query
          name: n
          schema:
            type: integer
          required: false
          description: Maximum number of returned events
      responses:
        200:
          description: Success.
          content: application/json
          schema:
            type: object
            properties:
              position:
                type: integer
                description: The number of events that had already been returned before this call.
              events:
                type: array
                items: object
  /status:
    get:
      summary: Returns current status
      description: Returns the current status of the whole node.
      responses:
        200:
          description: A JSON dictionary with various pieces of info per component.
          content:
            application/json:
              schema:
                type: dict
