---
openapi: 3.0.0
info:
  title: VAST Rest API
  version: 0.1
  description: "\nThis API can be used to interact with a VAST Node in a RESTful manner.\n\nAll API requests must be authenticated with a valid token, which must be\nsupplied in the `X-VAST-Token` request header. The token can be generated\non the command-line using the `vast rest generate-token` command."
servers:
  - url: https://vast.example.com/api/v0
security:
  - VastToken:
      []
components:
  securitySchemes:
    VastToken:
      type: apiKey
      in: header
      name: X-VAST-Token
paths:
  /export:
    get:
      summary: Export data
      description: Export data from VAST according to a query. The query must be a valid expression in the (VAST Query Language)[https://vast.io/docs/understand-vast/query-language].
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
          description: The query to execute.
          example: :ip in 10.42.0.0/16
        - in: query
          name: limit
          schema:
            type: integer
          required: false
          description: Maximum number of returned events
          example: 3
      responses:
        200:
          description: The result data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  num_events:
                    type: integer
                  version:
                    type: string
                  events:
                    type: array
                    items: object
                example:
                  version: v2.3.0-169-ge42a9652e5-dirty
                  events:
                    - "{\"timestamp\": \"2011-08-14T05:38:55.549713\", \"flow_id\": 929669869939483, \"pcap_cnt\": null, \"vlan\": null, \"in_iface\": null, \"src_ip\": \"147.32.84.165\", \"src_port\": 138, \"dest_ip\": \"147.32.84.255\", \"dest_port\": 138, \"proto\": \"UDP\", \"event_type\": \"netflow\", \"community_id\": null, \"netflow\": {\"pkts\": 2, \"bytes\": 486, \"start\": \"2011-08-12T12:53:47.928539\", \"end\": \"2011-08-12T12:53:47.928552\", \"age\": 0}, \"app_proto\": \"failed\"}"
                    - "{\"timestamp\": \"2011-08-12T13:00:36.378914\", \"flow_id\": 269421754201300, \"pcap_cnt\": 22569, \"vlan\": null, \"in_iface\": null, \"src_ip\": \"147.32.84.165\", \"src_port\": 1027, \"dest_ip\": \"74.125.232.202\", \"dest_port\": 80, \"proto\": \"TCP\", \"event_type\": \"http\", \"community_id\": null, \"http\": {\"hostname\": \"cr-tools.clients.google.com\", \"url\": \"/service/check2?appid=%7B430FD4D0-B729-4F61-AA34-91526481799D%7D&appversion=1.3.21.65&applang=&machine=0&version=1.3.21.65&osversion=5.1&servicepack=Service%20Pack%202\", \"http_port\": null, \"http_user_agent\": \"Google Update/1.3.21.65;winhttp\", \"http_content_type\": null, \"http_method\": \"GET\", \"http_refer\": null, \"protocol\": \"HTTP/1.1\", \"status\": null, \"redirect\": null, \"length\": 0}, \"tx_id\": 0}"
                    - "{\"timestamp\": \"2011-08-14T05:38:55.549713\", \"flow_id\": 929669869939483, \"pcap_cnt\": null, \"vlan\": null, \"in_iface\": null, \"src_ip\": \"147.32.84.165\", \"src_port\": 138, \"dest_ip\": \"147.32.84.255\", \"dest_port\": 138, \"proto\": \"UDP\", \"event_type\": \"netflow\", \"community_id\": null, \"netflow\": {\"pkts\": 2, \"bytes\": 486, \"start\": \"2011-08-12T12:53:47.928539\", \"end\": \"2011-08-12T12:53:47.928552\", \"age\": 0}, \"app_proto\": \"failed\"}"
                    - "null"
                  num_events: 3
        401:
          description: Not authenticated.
        422:
          description: Invalid query string or invalid limit.
  /status:
    get:
      summary: Return current status
      description: Returns the current status of the whole node.
      responses:
        200:
          description: OK.
          content:
            application/json:
              schema:
                type: dict
              example:
                catalog:
                  num-partitions: 7092
                  memory-usage: 52781901584
                version:
                  VAST: v2.3.0-rc3-32-g8529a6c43f
        401:
          description: Not authenticated.
