version: "3"
services:
  vast:
    image: tenzir/vast:${VAST_VERSION:-latest}
    environment:
      - VAST_ENDPOINT=vast:42000
    ports:
      - ${VAST_PORT:-42000}:42000
    command:
      - start
    networks:
      - vast

networks:
  vast:
    driver: bridge
