version: "3"
services:
  vast:
    environment:
      - VAST_START__COMMANDS=web server
      - VAST_PLUGINS__WEB__MODE=dev
      - VAST_PLUGINS__WEB__BIND=0.0.0.0
      - VAST_PLUGINS__WEB__PORT=42001
    ports:
      - ${VAST_WEB_PORT:-42001}:42001
