version: "3"
services:
  vast:
    # TODO: Consider switching from latest to stable by default, which offers a
    # better user experience. We can only do this after the release of VAST v2.4
    # at the earliest, which will be the first release to offer a stable tag for
    # Docker Hub.
    image: ${VAST_CONTAINER_REGISTRY:-docker.io}/tenzir/vast:${VAST_CONTAINER_REF:-latest}
    environment:
      - VAST_ENDPOINT=vast:42000
    ports:
      - ${VAST_PORT:-42000}:42000
    command:
      - start
    networks:
      - vast

networks:
  vast:
    driver: bridge
