version: "3"
services:
  vast:
    image: ${VAST_CONTAINER_REGISTRY:-docker.io}/tenzir/vast:${VAST_CONTAINER_REF:-latest}
    environment:
      - VAST_ENDPOINT=vast:42000
    ports:
      - ${VAST_PORT:-42000}:42000
    command:
      - start
    networks:
      - vast

networks:
  vast:
    driver: bridge
