logging:
  console: true
  console-verbosity: DEBUG
  file: false
  file-verbosity: DEBUG
  filename: vast.log

# How to pass in a vast.yaml? This way?
node:
  config: vast.yaml

apps:
  misp:
    api:
      host: http://localhost:5000
      key: demodemodemodemodemodemodemodemodemodemo
    zmq:
      host: localhost
      port: 50000
  thehive:
    user: demo@tenzir.com
    host: http://localhost:9000
    key: O8fD7Se+GPfAstfpxByzP8kTt5A4kQYi
