version: "3"
services:
  thehive-app:
    network_mode: host # currently for development, run VAST on host system
    image: ${VAST_CONTAINER_REGISTRY:-docker.io}/tenzir/vast-poetry:${VAST_CONTAINER_REF:-latest}
    volumes:
      - bindings-cache:/home/vast/.cache
      - ./app/:/opt/thehive/app  # relative paths must match on host and in the container
      - ../../python/:/python
    working_dir: /opt/thehive/app
    entrypoint:
      - bash
      - -c
      - "poetry install && poetry run run-app"
volumes:
  bindings-cache:
