version: "3.8"
services:
  neuron:
    network_mode: "service:vast" # used for tests only
    links:
      - "vast:vast"
  cortex:
    environment:
      - CORTEX_NETWORK_MODE=service:vast
    depends_on:
      - vast
  thehive:
    environment:
      - VAST_HOSTNAME=vast:42000
