version: "3"
services:
  thehive-app:
    image: ${VAST_CONTAINER_REGISTRY:-docker.io}/tenzir/vast-poetry:${VAST_CONTAINER_REF:-latest}
    volumes:
      - bindings-cache:/home/vast/.cache
      - ./app/:/opt/thehive/app # relative paths must match on host and in the container
      - ../../python/:/python
    working_dir: /opt/thehive/app
    command: run-app
    environment:
      - THEHIVE_URL=http://thehive:9000
      - VAST_ENDPOINT=vast:42000
      - BACKFILL_LIMIT=${BACKFILL_LIMIT:-100}
    depends_on:
      - vast
      - thehive
    networks:
      - vast
  thehive:
    networks:
      - vast
volumes:
  bindings-cache:
