name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - v*
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugins/web/ui
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Download latest vast-static build
        # and export its location as an environment variable
        # so that we can use it from playwright
        run: |
          wget https://storage.googleapis.com/tenzir-public-data/vast-static-builds/vast-static-latest.tar.gz
          tar -xzf vast-static-latest.tar.gz
          echo "VAST_STATIC_BIN=$(pwd)/opt/vast/bin/vast" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
