project:
  render:
    - docs/**/*.qmd
    - blog/**/*.qmd
  execute-dir: file
execute:
  cache: true
  warning: false
  error: false
knitr:
  opts_chunk:
    dev: "svglite"
    dev.args: transparent
format:
  gfm:
    keep-yaml: true
    fig-format: svg
    wrap: preserve
# For the lack of native code folding, we use our own extension that respects
# the "code-fold: true" attribute. This may be come obsolete in the future; see
# also: https://github.com/quarto-dev/quarto-cli/issues/2279.
filters:
  - codeblock-details
  - inline-svg
